import { SqlTaskDefinition } from "@/lib/types";

export const sqlWeekTwoId = "sql-week-02";

export const sqlWeekTwoTasks: SqlTaskDefinition[] = [
  {
    id: "sql-week-02-task-01",
    weekId: sqlWeekTwoId,
    stepNumber: 1,
    title: "Filter only active customers",
    difficulty: "easy",
    objective: "Use a basic WHERE clause with one exact condition.",
    instructions: [
      "Return `customer_id`, `customer_name`, and `is_active` from `customers`.",
      "Only include rows where the customer is active.",
    ],
    starterSql: "",
    solutionSql: "SELECT customer_id, customer_name, is_active\nFROM customers\nWHERE is_active = 1;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-02",
    weekId: sqlWeekTwoId,
    stepNumber: 2,
    title: "Filter only US customers",
    difficulty: "easy",
    objective: "Use WHERE on a text column.",
    instructions: [
      "Return `customer_id`, `customer_name`, and `country`.",
      "Only include customers from the US.",
    ],
    starterSql: "",
    solutionSql: "SELECT customer_id, customer_name, country\nFROM customers\nWHERE country = 'US';",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-03",
    weekId: sqlWeekTwoId,
    stepNumber: 3,
    title: "Paid orders only",
    difficulty: "easy",
    objective: "Filter transactional rows by status.",
    instructions: [
      "Return `order_id`, `status`, and `amount` from `orders`.",
      "Only include paid orders.",
    ],
    starterSql: "",
    solutionSql: "SELECT order_id, status, amount\nFROM orders\nWHERE status = 'paid';",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-04",
    weekId: sqlWeekTwoId,
    stepNumber: 4,
    title: "Use a greater-than filter",
    difficulty: "easy",
    objective: "Filter by a numeric threshold.",
    instructions: [
      "Return `order_id` and `amount` for orders above 200.",
      "Sort by `amount` descending.",
    ],
    starterSql: "",
    solutionSql: "SELECT order_id, amount\nFROM orders\nWHERE amount > 200\nORDER BY amount DESC;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-05",
    weekId: sqlWeekTwoId,
    stepNumber: 5,
    title: "Use a less-than filter",
    difficulty: "easy",
    objective: "Filter by the opposite numeric direction.",
    instructions: [
      "Return `order_id`, `amount`, and `status` for orders under 100.",
      "Sort by `order_id`.",
    ],
    starterSql: "",
    solutionSql: "SELECT order_id, amount, status\nFROM orders\nWHERE amount < 100\nORDER BY order_id;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-06",
    weekId: sqlWeekTwoId,
    stepNumber: 6,
    title: "Combine two conditions with AND",
    difficulty: "easy",
    objective: "Apply multiple filters at the same time.",
    instructions: [
      "Return active customers from the US.",
      "Show `customer_id`, `customer_name`, `country`, and `is_active`.",
    ],
    starterSql: "",
    solutionSql: "SELECT customer_id, customer_name, country, is_active\nFROM customers\nWHERE country = 'US'\n  AND is_active = 1;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-07",
    weekId: sqlWeekTwoId,
    stepNumber: 7,
    title: "Combine two values with OR",
    difficulty: "easy",
    objective: "Use OR for alternative matches.",
    instructions: [
      "Return customers from the US or Canada.",
      "Show `customer_id`, `customer_name`, and `country`.",
      "Sort by `customer_id`.",
    ],
    starterSql: "",
    solutionSql: "SELECT customer_id, customer_name, country\nFROM customers\nWHERE country = 'US'\n   OR country = 'Canada'\nORDER BY customer_id;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-08",
    weekId: sqlWeekTwoId,
    stepNumber: 8,
    title: "Use IN for multiple statuses",
    difficulty: "medium",
    objective: "Write cleaner multi-value filters.",
    instructions: [
      "Return orders where status is `paid` or `pending`.",
      "Show `order_id`, `status`, and `amount`.",
      "Sort by `order_id`.",
    ],
    starterSql: "",
    solutionSql: "SELECT order_id, status, amount\nFROM orders\nWHERE status IN ('paid', 'pending')\nORDER BY order_id;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-09",
    weekId: sqlWeekTwoId,
    stepNumber: 9,
    title: "Use BETWEEN on amounts",
    difficulty: "medium",
    objective: "Filter within an inclusive numeric range.",
    instructions: [
      "Return orders with amount between 90 and 200 inclusive.",
      "Show `order_id`, `amount`, and `status`.",
      "Sort by `amount` ascending.",
    ],
    starterSql: "",
    solutionSql: "SELECT order_id, amount, status\nFROM orders\nWHERE amount BETWEEN 90 AND 200\nORDER BY amount;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-10",
    weekId: sqlWeekTwoId,
    stepNumber: 10,
    title: "Use LIKE for text matching",
    difficulty: "medium",
    objective: "Use pattern matching on strings.",
    instructions: [
      "Return customers whose name starts with `A`.",
      "Show `customer_id` and `customer_name`.",
    ],
    starterSql: "",
    solutionSql: "SELECT customer_id, customer_name\nFROM customers\nWHERE customer_name LIKE 'A%';",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-11",
    weekId: sqlWeekTwoId,
    stepNumber: 11,
    title: "Find missing emails",
    difficulty: "medium",
    objective: "Handle NULL correctly with IS NULL.",
    instructions: [
      "Return customers that do not have an email address.",
      "Show `customer_id`, `customer_name`, and `email`.",
    ],
    starterSql: "",
    solutionSql: "SELECT customer_id, customer_name, email\nFROM customers\nWHERE email IS NULL;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-12",
    weekId: sqlWeekTwoId,
    stepNumber: 12,
    title: "Find non-null emails",
    difficulty: "medium",
    objective: "Use IS NOT NULL for the opposite case.",
    instructions: [
      "Return customers who do have an email address.",
      "Show `customer_id`, `customer_name`, and `email`.",
      "Sort by `customer_id`.",
    ],
    starterSql: "",
    solutionSql: "SELECT customer_id, customer_name, email\nFROM customers\nWHERE email IS NOT NULL\nORDER BY customer_id;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-13",
    weekId: sqlWeekTwoId,
    stepNumber: 13,
    title: "Filter by date range",
    difficulty: "medium",
    objective: "Apply a time-based filter cleanly.",
    instructions: [
      "Return orders placed on or after `2026-04-10` and on or before `2026-04-20`.",
      "Show `order_id`, `order_date`, and `amount`.",
      "Sort by `order_date` ascending.",
    ],
    starterSql: "",
    solutionSql: "SELECT order_id, order_date, amount\nFROM orders\nWHERE order_date >= '2026-04-10'\n  AND order_date <= '2026-04-20'\nORDER BY order_date;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-14",
    weekId: sqlWeekTwoId,
    stepNumber: 14,
    title: "Use NOT to exclude rows",
    difficulty: "medium",
    objective: "Negate a business rule safely.",
    instructions: [
      "Return orders that are not cancelled.",
      "Show `order_id`, `status`, and `amount`.",
      "Sort by `order_id`.",
    ],
    starterSql: "",
    solutionSql: "SELECT order_id, status, amount\nFROM orders\nWHERE NOT status = 'cancelled'\nORDER BY order_id;",
    orderSensitive: true,
  },
  {
    id: "sql-week-02-task-15",
    weekId: sqlWeekTwoId,
    stepNumber: 15,
    title: "Week 2 filtering challenge",
    difficulty: "medium",
    objective: "Combine several filtering tools in one answer.",
    instructions: [
      "Return paid or pending orders with amount at least 75.",
      "Exclude `bank` payments.",
      "Show `order_id`, `status`, `amount`, and `payment_method`.",
      "Sort by `amount` descending.",
    ],
    starterSql: "",
    solutionSql: "SELECT order_id, status, amount, payment_method\nFROM orders\nWHERE status IN ('paid', 'pending')\n  AND amount >= 75\n  AND payment_method <> 'bank'\nORDER BY amount DESC;",
    orderSensitive: true,
  },
];

export const sqlWeekTwoUnlockMessage =
  "Complete all 15 Week 2 tasks with correct answers to keep climbing into advanced SQL levels.";
