import { SqlWeekDefinition } from "@/lib/types";
import {
  sqlWeekOneDataDictionary,
  sqlWeekOneId,
  sqlWeekOneSchema,
  sqlWeekOneTasks,
  sqlWeekOneUnlockMessage,
} from "@/lib/sql-week-one";
import { sqlWeekThreeId, sqlWeekThreeTasks, sqlWeekThreeUnlockMessage } from "@/lib/sql-week-three";
import { sqlWeekTwoId, sqlWeekTwoTasks, sqlWeekTwoUnlockMessage } from "@/lib/sql-week-two";
import { sqlWeekFourId, sqlWeekFourTasks, sqlWeekFourUnlockMessage } from "@/lib/sql-week-four";
import {
  sqlWeekEightId,
  sqlWeekEightTasks,
  sqlWeekEightUnlockMessage,
  sqlWeekEighteenId,
  sqlWeekEighteenTasks,
  sqlWeekEighteenUnlockMessage,
  sqlWeekElevenId,
  sqlWeekElevenTasks,
  sqlWeekElevenUnlockMessage,
  sqlWeekFifteenId,
  sqlWeekFifteenTasks,
  sqlWeekFifteenUnlockMessage,
  sqlWeekFiveId,
  sqlWeekFiveTasks,
  sqlWeekFiveUnlockMessage,
  sqlWeekFourteenId,
  sqlWeekFourteenTasks,
  sqlWeekFourteenUnlockMessage,
  sqlWeekNineteenId,
  sqlWeekNineteenTasks,
  sqlWeekNineteenUnlockMessage,
  sqlWeekNineId,
  sqlWeekNineTasks,
  sqlWeekNineUnlockMessage,
  sqlWeekSevenId,
  sqlWeekSevenTasks,
  sqlWeekSevenUnlockMessage,
  sqlWeekSeventeenId,
  sqlWeekSeventeenTasks,
  sqlWeekSeventeenUnlockMessage,
  sqlWeekSixId,
  sqlWeekSixTasks,
  sqlWeekSixUnlockMessage,
  sqlWeekSixteenId,
  sqlWeekSixteenTasks,
  sqlWeekSixteenUnlockMessage,
  sqlWeekTenId,
  sqlWeekTenTasks,
  sqlWeekTenUnlockMessage,
  sqlWeekThirteenId,
  sqlWeekThirteenTasks,
  sqlWeekThirteenUnlockMessage,
  sqlWeekTwentyFourId,
  sqlWeekTwentyFourTasks,
  sqlWeekTwentyFourUnlockMessage,
  sqlWeekTwentyId,
  sqlWeekTwentyOneId,
  sqlWeekTwentyOneTasks,
  sqlWeekTwentyOneUnlockMessage,
  sqlWeekTwentyTasks,
  sqlWeekTwentyThreeId,
  sqlWeekTwentyThreeTasks,
  sqlWeekTwentyThreeUnlockMessage,
  sqlWeekTwentyTwoId,
  sqlWeekTwentyTwoTasks,
  sqlWeekTwentyTwoUnlockMessage,
  sqlWeekTwentyUnlockMessage,
  sqlWeekTwelveId,
  sqlWeekTwelveTasks,
  sqlWeekTwelveUnlockMessage,
} from "@/lib/sql-week-five-eight";

export const sqlDatasetSchema = sqlWeekOneSchema;
export const sqlDatasetDictionary = sqlWeekOneDataDictionary;

export const sqlWeekDefinitions: SqlWeekDefinition[] = [
  {
    id: sqlWeekOneId,
    badge: "SQL Week 1",
    title: "Write queries. Run them. Unlock the next step.",
    subtitle: "This week is only about SQL basics.",
    focus:
      "Pick a step, write the query, run it, and submit the correct result to unlock the next one.",
    unlockMessage: sqlWeekOneUnlockMessage,
    nextWeekId: sqlWeekTwoId,
    nextWeekLabel: "Go to Week 2",
    tasks: sqlWeekOneTasks,
  },
  {
    id: sqlWeekTwoId,
    badge: "SQL Week 2",
    title: "Master filtering, nulls, and boolean logic.",
    subtitle: "Week 2 is about writing precise predicates.",
    focus:
      "Use WHERE, AND, OR, IN, BETWEEN, LIKE, IS NULL, and NOT without introducing silent logic bugs.",
    unlockMessage: sqlWeekTwoUnlockMessage,
    nextWeekId: sqlWeekThreeId,
    nextWeekLabel: "Go to Week 3",
    tasks: sqlWeekTwoTasks,
  },
  {
    id: sqlWeekThreeId,
    badge: "SQL Week 3",
    title: "Join customers and orders with confidence.",
    subtitle: "Week 3 is about readable joins and cross-table thinking.",
    focus:
      "Use inner joins and left joins cleanly, keep track of row meaning, and combine filters across both tables.",
    unlockMessage: sqlWeekThreeUnlockMessage,
    nextWeekId: sqlWeekFourId,
    nextWeekLabel: "Go to Week 4",
    tasks: sqlWeekThreeTasks,
  },
  {
    id: sqlWeekFourId,
    badge: "SQL Week 4",
    title: "Aggregate joined data into real business metrics.",
    subtitle: "Week 4 moves from rows into grouped answers.",
    focus:
      "Use COUNT, SUM, AVG, GROUP BY, and HAVING to turn order-level data into customer and country level insights.",
    unlockMessage: sqlWeekFourUnlockMessage,
    nextWeekId: sqlWeekFiveId,
    nextWeekLabel: "Go to Week 5",
    tasks: sqlWeekFourTasks,
  },
  {
    id: sqlWeekFiveId,
    badge: "SQL Week 5",
    title: "Join, group, and reconcile warehouse facts.",
    subtitle: "Week 5 moves into intermediate data-engineering SQL.",
    focus: "Practice multi-table joins, HAVING, CTEs, date windows, and reconciliation checks.",
    unlockMessage: sqlWeekFiveUnlockMessage,
    nextWeekId: sqlWeekSixId,
    nextWeekLabel: "Go to Week 6",
    tasks: sqlWeekFiveTasks,
  },
  {
    id: sqlWeekSixId,
    badge: "SQL Week 6",
    title: "Build quality gates and debugging queries.",
    subtitle: "Week 6 focuses on finding data-quality problems before dashboards break.",
    focus: "Use null checks, conditional aggregation, joins, and source-to-target checks.",
    unlockMessage: sqlWeekSixUnlockMessage,
    nextWeekId: sqlWeekSevenId,
    nextWeekLabel: "Go to Week 7",
    tasks: sqlWeekSixTasks,
  },
  {
    id: sqlWeekSevenId,
    badge: "SQL Week 7",
    title: "Use windows and latest-record logic.",
    subtitle: "Week 7 introduces row-number style warehouse thinking.",
    focus: "Practice latest-record selection, deduplication, date logic, and grouped metrics.",
    unlockMessage: sqlWeekSevenUnlockMessage,
    nextWeekId: sqlWeekEightId,
    nextWeekLabel: "Go to Week 8",
    tasks: sqlWeekSevenTasks,
  },
  {
    id: sqlWeekEightId,
    badge: "SQL Week 8",
    title: "Reconcile business metrics end to end.",
    subtitle: "Week 8 completes the current 1000-question SQL milestone.",
    focus: "Combine joins, aggregates, CASE, CTEs, subqueries, windows, and data-quality checks.",
    unlockMessage: sqlWeekEightUnlockMessage,
    nextWeekId: sqlWeekNineId,
    nextWeekLabel: "Go to Week 9",
    tasks: sqlWeekEightTasks,
  },
  {
    id: sqlWeekNineId,
    badge: "SQL Week 9",
    title: "Advance into window-heavy SQL debugging.",
    subtitle: "Week 9 deepens latest-record, ranking, and exception logic.",
    focus: "Use window-style thinking, multi-step CTEs, and reconciliation filters.",
    unlockMessage: sqlWeekNineUnlockMessage,
    nextWeekId: sqlWeekTenId,
    nextWeekLabel: "Go to Week 10",
    tasks: sqlWeekNineTasks,
  },
  {
    id: sqlWeekTenId,
    badge: "SQL Week 10",
    title: "Practice cohort, funnel, and grouped metric patterns.",
    subtitle: "Week 10 turns warehouse rows into business-review answers.",
    focus: "Combine grouped metrics, CASE, date windows, and joined aggregations.",
    unlockMessage: sqlWeekTenUnlockMessage,
    nextWeekId: sqlWeekElevenId,
    nextWeekLabel: "Go to Week 11",
    tasks: sqlWeekTenTasks,
  },
  {
    id: sqlWeekElevenId,
    badge: "SQL Week 11",
    title: "Work through CDC and current-state style SQL.",
    subtitle: "Week 11 emphasizes changed-record and current-row reasoning.",
    focus: "Use CTEs, deduplication, latest-row selection, and data-quality exceptions.",
    unlockMessage: sqlWeekElevenUnlockMessage,
    nextWeekId: sqlWeekTwelveId,
    nextWeekLabel: "Go to Week 12",
    tasks: sqlWeekElevenTasks,
  },
  {
    id: sqlWeekTwelveId,
    badge: "SQL Week 12",
    title: "Debug metrics like a production data engineer.",
    subtitle: "Week 12 closes the 1500-question block and opens senior patterns.",
    focus: "Practice reconciliation, metric debugging, exception reporting, and warehouse-safe SQL.",
    unlockMessage: sqlWeekTwelveUnlockMessage,
    nextWeekId: sqlWeekThirteenId,
    nextWeekLabel: "Go to Week 13",
    tasks: sqlWeekTwelveTasks,
  },
  {
    id: sqlWeekThirteenId,
    badge: "SQL Week 13",
    title: "Measure retention, recency, and windowed behavior.",
    subtitle: "Week 13 pushes analytical SQL into data-engineering review work.",
    focus: "Practice latest records, date windows, grouped metrics, and exception-ready ordering.",
    unlockMessage: sqlWeekThirteenUnlockMessage,
    nextWeekId: sqlWeekFourteenId,
    nextWeekLabel: "Go to Week 14",
    tasks: sqlWeekThirteenTasks,
  },
  {
    id: sqlWeekFourteenId,
    badge: "SQL Week 14",
    title: "Audit current and historical dimension logic.",
    subtitle: "Week 14 focuses on SCD-style lookups and safe joins.",
    focus: "Use joins, CTEs, CASE logic, and latest-state checks without changing row grain.",
    unlockMessage: sqlWeekFourteenUnlockMessage,
    nextWeekId: sqlWeekFifteenId,
    nextWeekLabel: "Go to Week 15",
    tasks: sqlWeekFourteenTasks,
  },
  {
    id: sqlWeekFifteenId,
    badge: "SQL Week 15",
    title: "Detect changed records and reconcile systems.",
    subtitle: "Week 15 trains CDC-style thinking and warehouse validation.",
    focus: "Find source-target mismatches, quality exceptions, and duplicate-safe metric outputs.",
    unlockMessage: sqlWeekFifteenUnlockMessage,
    nextWeekId: sqlWeekSixteenId,
    nextWeekLabel: "Go to Week 16",
    tasks: sqlWeekFifteenTasks,
  },
  {
    id: sqlWeekSixteenId,
    badge: "SQL Week 16",
    title: "Debug incident metrics under production constraints.",
    subtitle: "Week 16 closes the 2000-question block and opens final senior review work.",
    focus: "Combine windows, CTEs, joins, dates, reconciliation, and exception reports.",
    unlockMessage: sqlWeekSixteenUnlockMessage,
    nextWeekId: sqlWeekSeventeenId,
    nextWeekLabel: "Go to Week 17",
    tasks: sqlWeekSixteenTasks,
  },
  {
    id: sqlWeekSeventeenId,
    badge: "SQL Week 17",
    title: "Recover ordered sessions and event behavior.",
    subtitle: "Week 17 focuses on ordered events, gaps, and latest-state reasoning.",
    focus: "Practice event ordering, date windows, deduplication, and exception reports.",
    unlockMessage: sqlWeekSeventeenUnlockMessage,
    nextWeekId: sqlWeekEighteenId,
    nextWeekLabel: "Go to Week 18",
    tasks: sqlWeekSeventeenTasks,
  },
  {
    id: sqlWeekEighteenId,
    badge: "SQL Week 18",
    title: "Balance ledger-style metrics and source totals.",
    subtitle: "Week 18 emphasizes finance-grade reconciliation and metric trust.",
    focus: "Use grouped checks, CASE logic, captured payments, refunds, and joined validations.",
    unlockMessage: sqlWeekEighteenUnlockMessage,
    nextWeekId: sqlWeekNineteenId,
    nextWeekLabel: "Go to Week 19",
    tasks: sqlWeekEighteenTasks,
  },
  {
    id: sqlWeekNineteenId,
    badge: "SQL Week 19",
    title: "Resolve identity and row-grain conflicts.",
    subtitle: "Week 19 trains duplicate-safe customer, order, and event reasoning.",
    focus: "Practice left joins, latest rows, grouped checks, and deterministic tie-breaking.",
    unlockMessage: sqlWeekNineteenUnlockMessage,
    nextWeekId: sqlWeekTwentyId,
    nextWeekLabel: "Go to Week 20",
    tasks: sqlWeekNineteenTasks,
  },
  {
    id: sqlWeekTwentyId,
    badge: "SQL Week 20",
    title: "Repair late-arriving facts and dimensions.",
    subtitle: "Week 20 focuses on temporal filters and source-target readiness.",
    focus: "Use date boundaries, effective-state thinking, CTEs, and reconciliation outputs.",
    unlockMessage: sqlWeekTwentyUnlockMessage,
    nextWeekId: sqlWeekTwentyOneId,
    nextWeekLabel: "Go to Week 21",
    tasks: sqlWeekTwentyTasks,
  },
  {
    id: sqlWeekTwentyOneId,
    badge: "SQL Week 21",
    title: "Build operational SLA and exception views.",
    subtitle: "Week 21 turns warehouse rows into operational monitoring checks.",
    focus: "Practice shipment, payment, event, and appointment exception reporting.",
    unlockMessage: sqlWeekTwentyOneUnlockMessage,
    nextWeekId: sqlWeekTwentyTwoId,
    nextWeekLabel: "Go to Week 22",
    tasks: sqlWeekTwentyOneTasks,
  },
  {
    id: sqlWeekTwentyTwoId,
    badge: "SQL Week 22",
    title: "Validate snapshots and current-state outputs.",
    subtitle: "Week 22 checks consistency between raw rows and analytical snapshots.",
    focus: "Use ranking, current-state selection, grouped metrics, and null-safe checks.",
    unlockMessage: sqlWeekTwentyTwoUnlockMessage,
    nextWeekId: sqlWeekTwentyThreeId,
    nextWeekLabel: "Go to Week 23",
    tasks: sqlWeekTwentyTwoTasks,
  },
  {
    id: sqlWeekTwentyThreeId,
    badge: "SQL Week 23",
    title: "Make backfills and retries safe.",
    subtitle: "Week 23 focuses on replay-safe extracts and deterministic output contracts.",
    focus: "Practice watermarks, date windows, source filters, and stable ordering.",
    unlockMessage: sqlWeekTwentyThreeUnlockMessage,
    nextWeekId: sqlWeekTwentyFourId,
    nextWeekLabel: "Go to Week 24",
    tasks: sqlWeekTwentyThreeTasks,
  },
  {
    id: sqlWeekTwentyFourId,
    badge: "SQL Week 24",
    title: "Complete the senior warehouse SQL review.",
    subtitle: "Week 24 completes the 3000-question SQL bank.",
    focus: "Combine joins, windows, CTEs, reconciliation, data quality, and incident-ready SQL.",
    unlockMessage: sqlWeekTwentyFourUnlockMessage,
    nextWeekId: null,
    nextWeekLabel: null,
    tasks: sqlWeekTwentyFourTasks,
  },
];

export const sqlAllTasks = sqlWeekDefinitions.flatMap((week) => week.tasks);

export const getSqlWeekDefinition = (weekId: string) =>
  sqlWeekDefinitions.find((week) => week.id === weekId) ?? null;
